---
title: "Ejercicios sobre estructuras de datos"
author: "Juan Gabriel Gomila & María Santos"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

## Ejercicio 1

Dad la entrada (2,2) de $A\cdot (A+A )\cdot A$, con $$A = \begin{pmatrix} 1 & 3\\ 2 & 4\end{pmatrix}$$

```{r}
A=matrix(c(1,2,3,4), ncol = 2)
Tot=A%*%(A+A)%*%A
Tot
```

## Ejercicio 2

Dad los valores propios de la matriz $$B = \begin{pmatrix} 2 & 4 & -6\\ 0 & 0 & 3\\ 0 & -2 & 5\end{pmatrix}$$

```{r}
B= eigen(matrix(c(2,0,0,4,0,-2,-6,3,5), ncol = 3))$values
B
```


## Ejercicio 3

Dad, redondeando a 3 cifras decimales, los vectores propios de la matriz $$C = \begin{pmatrix} -48 & 35 & -12\\ -134 & 95 & -32\\ -194 & 133 & -44\end{pmatrix}$$

```{r}
C= round(eigen(matrix(c(-48,-134,-194,35,95,133,-12,-32,-44), ncol = 3))$vectors, 3)
C
```

## Ejercicio 4

Dad el rango de la matriz $$D = \begin{pmatrix} -2 & -8 & -2 & 3\\ -3 & -6 & -1 & 2\\ -9 & -22 & -3 & 7\\ -18 & -44 & -8 & 15\end{pmatrix}$$

```{r}
D= qr(matrix(c(-2,-3,-9,-18,-8,-6,-22,-44,-2,-1,-3,-8,3,2,7,15), ncol = 4))$rank
D
```
