---
title: "Distribución de Bernoulli"
author: "Curso de Estadística Descriptiva"
date: "21/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Función de densidad
Sea $X = Be(p=0.7)$, la distribución que modela la probabilidad de obtener una cara usando una moneda trucada. 

$$f(k) = p^k(1-p)^{1-p},\ k\in \{0,1\}$$

## En R


```{r}
library(Rlab)
dbern(0, prob= 0.7) #funcion densidad que la moneda sea 0
dbern(1, prob = 0.7) #funcion densidad que la moneda sea 1
pbern(0, prob = 0.7) #funcion de probabilidad acumulada para 0
pbern(1, prob = 0.7) #funcion de probabilidad acumulada para 1
qbern(0.5, prob = 0.7) #cuantil en 0.5
qbern(0.25, prob = 0.7) #cuantil en 0.25
rbern(100, prob = 0.7) -> data #generamos 100 numeros aleatorios 0 y 1, y los metemos en data
hist(data)
```

## En Python

```{python}
from scipy.stats import bernoulli
import matplotlib.pyplot as plt
p = 0.7
mean, var, skew, kurt = bernoulli.stats(p, moments = 'mvsk')
print("Media %f"%mean)
print("Varianza %f"%var)
print("Sesgo %f"%skew)
print("Curtosis %f"%kurt)

fix, ax = plt.subplots(1,1)
x = bernoulli.rvs(p, size = 1000)
ax.hist(x)
plt.show()
```

