---
title: "Binomial"
author: "Curso de Estadística Descriptiva"
date: "4/2/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Función de densidad
Sea $X = B(n = 30, p = 0.6)$,

TODO: escribir la FDens y la FDistr

## En `R`

```{r}
library(Rlab)
n = 30
p = 0.6
#densidad binomial(probabilid de sacar entre 0 y 30 exitos sabiendo que el tamaño es n y que su probabilidad es 0.6)
plot(0:n, dbinom(0:n, size = n, prob = p)) 

plot(0:n, pbinom(0:n, size = n, prob = p)) #probabilidad acumulada binomial 
qbinom(0.5, n, p) #cuantil para 0.5
qbinom(0.25, n, p) #primer cuartil
hist(rbinom(100000, n, p), breaks = 0:30) #hasta el INF daría la de densidad
```

## En Python

```{python}
from scipy.stats import binom 
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1,1)
n = 7
p = 0.4

mean, var, skew, kurt = binom.stats(n, p, moments = 'mvsk')

print("Media %f"%mean)
print("Varianza %f"%var)
print("Sesgo %f"%skew)
print("Curtosis %f"%kurt)


x = np.arange(0, n+1)
ax.plot(x, binom.pmf(x, n, p), 'bo', ms = 8, label = "Función de densidad de B(7,0.4)")
ax.vlines(x, 0, binom.pmf(x,n,p), colors = 'b', lw = 4, alpha = 0.5)

rv = binom(n,p)
ax.vlines(x,0, rv.pmf(x), colors = 'k', linestyles='--', lw = 1, label = "Distribución teórica")

ax.legend(loc = 'best', frameon = False)

plt.show()


fix, ax = plt.subplots(1,1)
r = binom.rvs(n, p, size = 10000)
ax.hist(r, bins = n)
plt.show()
```

